import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from pathlib import Path

# Paths
base_dir = Path(__file__).parent.parent.parent
output_pdf = base_dir / 'docs' / 'CBCI_LinkedIn_Carousel.pdf'

# Slide Data
slides = [
    {
        "title": "Who Really Controls\nthe Economy?",
        "content": "In 2022, global inflation targets shattered.\nForward guidance failed. Market volatility spiked.\n\nHow do we quantify 'trust' in monetary policy?",
        "insight": "Institutional credibility is no longer an abstract feeling\n—it’s a measurable, tradable asset."
    },
    {
        "title": "Introducing the CBCI",
        "content": "The Central Bank Credibility Index (CBCI)\nmathematically tracks the performance, consistency,\nand market trust of the world's top 10 central banks\nfrom 2010 to 2026.",
        "insight": "We applied a quantitative lens\nto the world's most qualitative problem."
    },
    {
        "title": "Pillar 1: Inflation\nAnchoring (30%)",
        "content": "The primary mandate.\n\nWe measure the absolute deviation of headline\ninflation from official targets over a\nrolling 12-month window.",
        "insight": "A central bank that cannot hit its stated target\nloses its primary economic anchor."
    },
    {
        "title": "Pillar 2: Policy\nConsistency (20%)",
        "content": "Do they actually do what they say?\n\nWe use Natural Language Processing (NLP) to score\npolicy statements and check alignment\nwith subsequent rate moves.",
        "insight": "Communication is a policy tool.\nContradictory actions destroy yield curves."
    },
    {
        "title": "Pillars 3 & 4:\nMarket Trust (30%)",
        "content": "We track the rolling volatility of sovereign bonds\nand currency pairs.\n\nWe also factor in the central bank's own\nforecasting error (MAE).",
        "insight": "Markets vote on a central bank's credibility\nevery millisecond."
    },
    {
        "title": "Institutional-Grade\nTech Stack",
        "content": "Built for massive scale and reproducibility.\n\nAutomated ETL pipelines ingesting millions of rows\nof macro data and text.",
        "insight": "Robust, automated data pipelines are the\nfoundation of reliable macro insights."
    },
    {
        "title": "The Forecasting\n'Blind Spot'",
        "content": "The data reveals exactly which central banks\nconsistently fail to predict their own mandates,\npenalizing them for systemic forecasting errors.",
        "insight": "Habitual forecasting errors precede\nmajor policy blunders."
    },
    {
        "title": "The 'Shock' Quadrant",
        "content": "Some central banks communicated 'Dovish' immediately\nbefore aggressively hiking rates.\n\nThe CBCI quantifies exactly when these\nmarket-breaking shocks occurred.",
        "insight": "Words move markets—until they\ndirectly contradict actions."
    },
    {
        "title": "The Gold Standard\n(2026)",
        "content": "Which central bank maintained extreme FX stability\nand tight inflation anchoring through the turbulence\nof the 2020s?",
        "insight": "True institutional credibility is forged in crises."
    },
    {
        "title": "The Fall From Grace",
        "content": "The 'Transitory Inflation' narrative caused the\nsteepest credibility drawdowns in modern history,\nseverely impacting short-term bond market confidence.",
        "insight": "Rebuilding market trust takes years;\nlosing it takes one missed forecast."
    },
    {
        "title": "Why This Matters\nto the Buy-Side",
        "content": "For strategists at JPMorgan or BlackRock, the CBCI\nprovides a direct quantitative overlay for sovereign\ndebt risk pricing and FX VaR models.",
        "insight": "Alpha is generated by front-running shifts\nin institutional credibility."
    },
    {
        "title": "Explore the Data",
        "content": "Want to explore the interactive dashboard and dive\ninto the open-source Python architecture?",
        "insight": "Check out the complete methodology and codebase\non my GitHub! 👇 [Link in comments]"
    }
]

def draw_slide(pdf, slide_data, page_num, total_pages):
    fig, ax = plt.subplots(figsize=(10.8, 10.8)) # Square format for LinkedIn
    fig.patch.set_facecolor('#0d1117')
    ax.set_facecolor('#0d1117')
    
    # Title
    ax.text(0.1, 0.85, slide_data['title'], fontsize=38, fontweight='bold', color='#ffffff', ha='left', va='top')
    
    # Content
    ax.text(0.1, 0.55, slide_data['content'], fontsize=24, color='#c9d1d9', ha='left', va='center', linespacing=1.6)
    
    # Insight box
    ax.text(0.1, 0.25, slide_data['insight'], fontsize=20, color='#58a6ff', ha='left', va='center', style='italic',
            bbox=dict(boxstyle='round,pad=1', fc='#161b22', ec='#58a6ff', alpha=0.9))
            
    # Page number and Branding
    ax.text(0.9, 0.05, f"{page_num}/{total_pages}", fontsize=16, color='#8b949e', ha='center', va='center')
    ax.text(0.1, 0.05, "Central Bank Credibility Index (CBCI) | Anurag Singh", fontsize=16, color='#8b949e', ha='left', va='center')
    
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis('off')
    
    pdf.savefig(fig, bbox_inches='tight', facecolor=fig.get_facecolor())
    plt.close(fig)

def generate():
    with PdfPages(output_pdf) as pdf:
        for i, slide in enumerate(slides):
            draw_slide(pdf, slide, i+1, len(slides))
    print(f"Successfully generated carousel PDF at {output_pdf}")

if __name__ == '__main__':
    generate()
